stolostron/acmqe-mcn-test

lib/submariner_deploy/submariner_deploy.sh, lib/submariner_prepare/downstream_prepare.sh, lib/submariner_prepare/validate_acm_readiness.sh, variables
- Add support for versions:
- 2.7.0 / 0.14.0
- 2.5.4 / 0.12.2
- 2.5.5 / 0.12.2
- During fetch of IIB, the "delta" variable should be rewritten during each loop to not double the result.
- Print "Non Globalnet" warning only when unmatched cluster is found.
- Fix the string that prints how many gateway nodes deployed.
=> Add support for 0.14.0 version and minor fixes

README.md, lib/common/helper_functions.sh, lib/submariner_deploy/submariner_deploy.sh, lib/submariner_prepare/downstream_mirroring_workaround.sh, lib/submariner_test/submariner_test.sh, manifests/submariner-config.yaml, variables
- Add ARO support to submariner deployment.
- Add "loadBalancerEnable: true" parameter to SubmarinerConfig CR. Currently, parameter should be used by ARO and ROSA clusters only.
- Import downstream nettest image starting from 0.13.2 version.
- Add "set_cluster_platform_for_test_report" function to properly identify platform for test report file name.
- Add "get_cluster_platform" and "get_cluster_product" functions to detect information from both cluster types - imported and hive based.
- ARO and ROSA clusters skip cloud-prepare step, so passing "null" value as an input to cloud credentials of the cluster.
=> Add ARO support

lib/common/helper_functions.sh, lib/submariner_prepare/validate_acm_readiness.sh, lib/submariner_test/submariner_test.sh, run.sh
When a non globalnet submariner deployment is made, the flow checks for the cluster network configuration and compares to other clusters. If conflicting ranges detected, one of the cluster excluded from the deployment flow to prevent conflict during submariner deployment.
As ARO and ROSA could be only imported and not created by hive, an approach of fetching clusters information should change.
Fetch networking information directly from the clusters instead of clusterdeployment resource as imported cluster as not available there.
=> Run validation on imported clusters

.github/workflows/shellcheck.yml
The GitHub Action should be triggered on the 'main', 'devel' and all the 'release*' branches.
=> Update GH action trigger

lib/submariner_test/submariner_test.sh
The "subctl" e2e execution is using "--context" flags instead of direct kubeconfigs references.
=> Update e2e tests flags

lib/common/prerequisites.sh
When downloading subctl binary for testing, we need to get the submariner addon version.
Currently, during the version fetch the first available cluster taken from the clusterset.
The possible problem could be, that the clusterset contains clusters beside the clusters with submariner deployment.
As a result, addon version could not be fetched.
Modify the function to get the first cluster from the "MANAGED_CLUSTERS" variable that contains submariner clusters instead of the first cluster from the clusterset.
=> Modify submariner version fetch for test

README.md, lib/common/helper_functions.sh, lib/common/prerequisites.sh, lib/submariner_deploy/submariner_deploy.sh, lib/submariner_prepare/downstream_mirroring_workaround.sh, run.sh, variables
- The ACM 2.5.6 / Submariner 0.12.3 version should contains the flow related to that version only. Remove other versions dependencies.
- Remove manual selection of submariner version. Submariner version tied to ACM version.
=> [release-2.5] - Remove old versions dependencies

lib/submariner_prepare/validate_acm_readiness.sh
When fetching clusters for submariner deployment, it's not enough to test that the clusters have power state - "Running". If the cluster created from a pool and set to run but not yet claimed, it will be still showed in "Running" state.
Check for the clusters Availability from the managed clusters output in addition to the above check.
=> [release-2.6] - Validate clusters availability

lib/submariner_prepare/validate_acm_readiness.sh
When fetching clusters for submariner deployment, it's not enough to test that the clusters have power state - "Running". If the cluster created from a pool and set to run but not yet claimed, it will be still showed in "Running" state.
Check for the clusters Availability from the managed clusters output in addition to the above check.
=> [release-2.5] Validate clusters availability

README.md, cypress/package.json, lib/common/helper_functions.sh, lib/common/prerequisites.sh, lib/submariner_test/submariner_e2e.sh, lib/submariner_test/submariner_test.sh, lib/submariner_test/submariner_ui.sh, run.sh, variables
- Add cypress tests execution into the pipeline
- Split e2e and ui testing into different files. Both are called from the same "execute_submariner_tests" function.
- Cypress requires "npm" and "nodejs" installed as prerequisites. Since those packages requires admin privileges and can't be installed during ci pipeline execution, the pipeline will check the state of the environment for those packages. If package will be missing, cypress execution will be skipped.
- Add a new flag for testing execution - "--test-type". The flag controls execution of tests - e2e (api) and ui (cypress). By default, both testing methods will be mentioned, but a user count change it if needed.
- Refactor "combine_tests_basename" function to generate tests basenames for both e2e and ui testing.
=> Integrate Cypress into the test pipeline

README.md, cypress/package.json, lib/common/helper_functions.sh, lib/common/prerequisites.sh, lib/submariner_test/submariner_e2e.sh, lib/submariner_test/submariner_test.sh, lib/submariner_test/submariner_ui.sh, run.sh, variables
- Add cypress tests execution into the pipeline
- Split e2e and ui testing into different files. Both are called from the same "execute_submariner_tests" function.
- Cypress requires "npm" and "nodejs" installed as prerequisites. Since those packages requires admin privileges and can't be installed during ci pipeline execution, the pipeline will check the state of the environment for those packages. If package will be missing, cypress execution will be skipped.
- Add a new flag for testing execution - "--test-type". The flag controls execution of tests - e2e (api) and ui (cypress). By default, both testing methods will be mentioned, but a user count change it if needed.
- Refactor "combine_tests_basename" function to generate tests basenames for both e2e and ui testing.
=> [release-2.6] Integrate Cypress into the test pipeline (#153)

cypress/cypress/apis/clusterSet.js
In the versions below acm 2.7.0, cluster set is using api version "/apis/cluster.open-cluster-management.io/v1beta1". In the newer version of acm 2.7.0, the version has been increased to "/apis/cluster.open-cluster-management.io/v1beta2".
Update the "release-2.6" branch to use the relevant api version.
=> [release-2.6] Cypress - fix clusterset api version

lib/submariner_prepare/downstream_mirroring_workaround.sh
The image tag bug has been fixed.
Removing the workaround.
Reference - https://issues.redhat.com/browse/ACM-2387
=> Remove fixed subctl image workaround

manifests/cluster-set.yaml
In acm 2.7 the api version for the clusterset has been updated from: cluster.open-cluster-management.io/v1beta1
to
cluster.open-cluster-management.io/v1beta2
Update hte manifest file.
=> Update clusterset manifest api version

cypress/cypress/e2e/01_submariner_deployment_validation.cy.js, cypress/cypress/e2e/02_submariner_uninstall.cy.js
- Rename cypress test to create an order convention. The tests will be executed base on the numbering convention.
- Increase the uninstall test timeout to 5 minutes. This timeout currently suited by the following tested platforms: aws, gcp and azure.
=> Rename cypress tests

lib/submariner_deploy/submariner_deploy.sh
When checking for the 3 states of submariner readiness:
- Gateway
- Agent
- Connectivity
The check is done for each cluster used in deployment. The state check of each server needs to be reset on each iteration.
=> Fix submariner deploy check

.gitignore, cypress/cypress.config.js, cypress/package-lock.json, cypress/package.json
- Remove "@types/cypress" as deprecated. Starting from cypress version 10.0.0, the package has been implemented into the core of cypress.
- Update the deprecated "cypress-grep" by "@cypress/grep" and set the config into the cypress.config.js file.
- Update the package-lock.json file
- Add "cypress/node_modules/" to .gitignore to not catch it by git. Each system will build its own "node_modules" directory during install.
=> Update Cypress configuration

lib/submariner_test/submariner_ui.sh
During execution of cypress tests, if one of the tests fails, the command exit with non zero exist code.
Prevent this failure to provide the ability to gather logs for deployment.
=> Prevent pipeline failure because of cypress test fail

cypress/cypress/e2e/04_submariner_addon.cy.js
Add a test that:
- Create a cluster set
- check that the “Submariner Addon” tab exists
- Delete the test cluster set at the end
=> Add Submariner Addon tab test  to Cypress

Jenkinsfile
Due to a bug with cluster length in Azure platform [1] [2], remove the default execution of Azure platform from the Jenkins pipeline. Re-add once the bug is fixed.
[1] - https://bugzilla.redhat.com/show_bug.cgi?id=2118385 
[2] - https://issues.redhat.com/browse/ACM-2076
=> Remove Azure platform from default execution

lib/common/prerequisites.sh, lib/submariner_test/submariner_e2e.sh, run.sh, variables
Submariner deployment started to support references to images by digest instead of floating tags.
It allows to:
- Perform deployment and testing of ROSA platform
- Reduce deployment time by 20-25 minutes
Remove configuration of MachineSet and use instead ImageContentSourcePolaicy object creation.
Remove import of the images into internal cluster registry. The images will be fetched directly from the mirror registry.
Add "--image-override" argument to subctl binary to specify nettest image with digest reference.
=> Switch to digest deployment flow

lib/reporting/polarion.sh, lib/reporting/polarion_report.py
Polarion report script should be called with "python3" instead of "python", otherwise it's failed.
=> Fix polarion_report script call

lib/submariner_deploy/submariner_deploy.sh, manifests/submariner-config.yaml
The "startingCSV" parameter from Subscription section under SubmarinerConfig should not be used.
The Submariner install version will be set automatically to latest z version of the minur varsion based on the defined channel.
=> Remove "startingCSV" parameter from Submariner subscription

Jenkinsfile
Update Jenkinsfile to use a dedicated Submariner image by jenkins pipeline.
The Dockerfile could be seen in the root of the repository as well.
=> Update Jenkinsfile image

Jenkinsfile
- Remove "VERSION" parameter from Jenkinsfile that is not used in the deployment/test pipeline anymore.
- Explicitly define "downstream" argument for all the choises.
=> Remove unused param from Jenkinsfile

Jenkinsfile
Docker image has the following configuration within Jenkins file: "args '--network host -u 0:0'"
The "-u 0:0" sets the container to run as root.
It created the following error during cypress execution:
================
npm ERR! code 1
npm ERR! path /home/centos/workspace/qe-acm-automation-poc/submariner_e2e_tests/cypress/node_modules/cypress npm ERR! command failed
npm ERR! command sh -c node index.js --exec install npm ERR! Cypress cannot write to the cache directory due to file permissions npm ERR!
npm ERR! See discussion and possible solutions at
npm ERR! https://github.com/cypress-io/cypress/issues/1281 npm ERR!
npm ERR! ----------
npm ERR!
npm ERR! Failed to access /root/.cache/Cypress:
npm ERR!
npm ERR! EACCES: permission denied, mkdir '/root/.cache/Cypress'
================
Remove …
=> Remove "become root" from docker image in Jenkinsfile

Jenkinsfile, lib/submariner_deploy/submariner_deploy.sh, lib/submariner_test/submariner_e2e.sh
Add disruptive tests to e2e execution and perform deployment of two submariner gateways on one of the clusters to test fail-over scenario.
=> Add disruptive tests to e2e execution

cypress/cypress/e2e/04_submariner_addon.cy.js
Submariner_addon test fails randomly, when created clusterset takes a few seconds to appear sometimes.
If it does not appear right away, the test fails as it unable to find the expected clusterset.
Replace the "cy.get" with "cy.contains" and add a timeout for the clusterset expect after creation.
=> Fix Cypress "submariner_addon" test failure

lib/submariner_prepare/downstream_prepare.sh
Deployment of downstream submariner require a query from the datagrepper resource.
Datagrepper reside within red hat network, which means VPN is required to perform the query.
Add verification check and message to ensure that is not output received, the user should check the VPN connection.
=> Add connection check to datagrepper query

Jenkinsfile
According to acm-qe pipeline triggering when using "@api" and "@api-post-release" test tags only api tests should be executed.
https://issues.redhat.com/browse/ACM-3969
=> Execute API tests by tags

Jenkinsfile
Add option to execute only part of the pipeline.
For example, perform only submariner deployment.
Or execute only test phase.
The option will be exposed as parameter in jenkins job.
=> Add pipeline specific part to execute

roles/ocp/tasks/fetch_details.yml
Specify manifest directory as details output after cluster creation.
=> Print manifests dir path after cluster creation

roles/cluster_login/tasks/main.yml
The flow of variables assignment should be the following: If any of the "OC_CLUSTER_URL", "OC_CLUSTER_USER" or "OC_CLUSTER_PASS" environment variables exists, it should be used, otherwise, fall back to ansible "cluster_url", "cluster_user" and "cluster_pass" variables.
=> Fix env vars assignment on cluster_login role

roles/acm/tasks/deploy.yml, roles/acm/tasks/main.yml, roles/ocp/tasks/fetch_details.yml, roles/ocp/tasks/main.yml
- Validate CSV for for multiclusterhub subscription has been applied and suceeded before starting multiclusterhub deployment.
- Modify ocp and acm succeed output with cluster details.
- Add "no_log: true" to ocp required parameters validation to not print the pull_secret and ssh_pub_key into the console output.
=> Add CSV validation to MCH deployment

lib/submariner_test/submariner_test.sh
- Add clusters versions to the report in the following format: "ACM-2.8.0-Submariner-0.15.0-ARO-4.11-GCP-4.12-Globalnet"
- Recent builds of 2.8 deploy acm hub version which appends build number to the version - 2.8.0-62. Remove the build and leave only acm version.
=> Modify tests report names

cypress/cypress/e2e/02_submariner_uninstall.cy.js
The submariner uninstall cypress test started to fail because of the changed reference in clusters multiple selectors during submariner uninstall that happened in MCE 2.0.x version.
Fixing the flow.
=> Fix cypress submariner uninstall test

lib/common/prerequisites.sh
Currently, if run.sh is used for downstream and upstream tests, but runs into errors, the downloaded archives can be left in place, with different names: subctl-...-linux-amd64.tar.xz extracted from the downstream image, or subctl.tar.xz downloaded from GitHub.
Instead of keeping the image archive name, using subctl.tar.xz in all cases avoids such errors, and allows the script to be simplified; find no longer needs to be used, and the tar command can be directly given the right file name to use.
Similarly, the subctl binary can be handled using shell globs, without find. Using install instead of cp ensures that the file is executable after installation, regardless of its permissions in the archive.
=> Use a single subctl archive name

lib/common/prerequisites.sh
Currently, if run.sh is used for downstream and upstream tests, but runs into errors, the downloaded archives can be left in place, with different names: subctl-...-linux-amd64.tar.xz extracted from the downstream image, or subctl.tar.xz downloaded from GitHub.
Instead of keeping the image archive name, using subctl.tar.xz in all cases avoids such errors, and allows the script to be simplified; find no longer needs to be used, and the tar command can be directly given the right file name to use.
Similarly, the subctl binary can be handled using shell globs, without find. Using install instead of cp ensures that the file is executable after installation, regardless of its permissions in the archive.
Based on - https://github.com/stolostron/acmqe-mcn-test/pull/264
=> [release-2.6] - Use a single subctl archive name

cypress/cypress/e2e/02_submariner_uninstall.cy.js
Rever the following fix.
https://github.com/stolostron/acmqe-mcn-test/pull/263
In acm version 2.6.5, the reference still exists.
=> [release-2.6] Revert cypress uninstall fix

lib/submariner_test/submariner_test.sh
In acm 2.6, ocp major version available only in clusterdeployment and not in managedclusters.
=> [release-2.6] Fix ocp version fetch for report

cypress/cypress/e2e/02_submariner_uninstall.cy.js
Rever the following fix.
https://github.com/stolostron/acmqe-mcn-test/pull/263
In acm version 2.7.3, the reference still exists.
=> [release-2.7] Revert cypress uninstall fix

playbooks/env_deploy.yml, playbooks/env_destroy.yml, roles/acm/README.md, roles/ocp/README.md, roles/ocp/defaults/main.yml, roles/ocp/tasks/main.yml
- Align state variable across roles When using playbook with multiple roles (ocp, acm, managed_cluster) to create full environment, better to use single "state" variable for creation/deletion of the resources. The variable will be - `state` and accepted variables - preset/absent.
- Create a separate playbooks for env creation and env destroy.
=> Align state variable across roles

roles/acm/tasks/main.yml
On some environments, "api_found" return "true" although it doesn't exist.
Modify the check for installed acm hub by checking the resources list to be empty.
=> Modify check for install acm hub

roles/managed_cluster/tasks/cluster_deployment.yml, roles/managed_cluster/vars/main.yml
Images for managed cluster have number of architectures. In order to fetch the right image with the right architecture, add the cluster_architecture variable to fetch the exact image.
=> [managed_cluster role] Add images architecture selection

roles/ocp/README.md
The ofenshift version was written with "/" instead of with "."
=> Fix typo on ocp role README

roles/ocp/README.md, roles/ocp/defaults/main.yml, roles/ocp/tasks/main.yml, roles/ocp/tasks/prepare.yml, roles/ocp/templates/cloud-creds.j2
When deploying ocp cluster on machine which doesn't has cloud credentials configured, creation of the cloud will fail.
Add credentials set for credentials if not exists. Currently, adding "AWS" cloud credentials.
=> [OCP role] - Add cloud creds set

Jenkinsfile
The bug with cluster length in Azure platform [1] [2], has been fixed, re-adding the azure platform back to Jenkins pipeline.
[1] - https://bugzilla.redhat.com/show_bug.cgi?id=2118385
[2] - https://issues.redhat.com/browse/ACM-2076
=> Re-add Azure platform to Jenkinsfile

cypress/cypress/e2e/02_submariner_uninstall.cy.js
cypress uninstall test failed because some CSS elements changed on ocp 4.13.
=> Fix cypress uninstall test

cypress/cypress/support/commands.js
In Cypress tests, when connecting the hub, the password that typed could be seen. Now, when typing the password, or any string element that is defined as sensitive, it is replaced with asterisks (*).
=> Hide sensitive data in the source code (Cypress tests)

Dockerfile
The "pip install" command should not contain "--no-deps" argument, othervise next command will fail.
=> Remove "--no-deps" argument from Dockerfile

Jenkinsfile
Remove "--test-type" argument from Jenkinsfile as it's not supported in ACM version 2.5.x.
=> Remove "--test-type" argument from Jenkinsfile

roles/ocp/README.md, roles/ocp/defaults/main.yml, roles/ocp/tasks/deploy.yml
When deploying ocp, we could choose a version of the openshift. By default it supports deployment from "stable" channel. Add support for other channels like, "latest" and "candidate".
=> Add "openshift_channel" to the ocp role.

README.md, lib/common/helper_functions.sh, lib/submariner_test/submariner_test.sh, run.sh, variables
The content of this variable is determined using flag (--report_suffix) that was added. 
It was added in order to distinguish between the different features that are tested, for example backup and restore.
=> Add "report_suffix" variable to the end of the tests basename string.

roles/ocp/defaults/main.yml, roles/ocp/tasks/fetch_details.yml, roles/ocp/tasks/main.yml
Once creation of the clusters completes with "ocp" role, generate a "clusters_details.yml" file that will hold connection details for the clusters.
This file will be used to fetch connection details of the clusters by other roles.
=> Generate clusters connection details file

roles/cluster_login/defaults/main.yml, roles/cluster_login/tasks/main.yml
The "cluster_login" role fetch openshift login token from environment varialbes.
As newly created ocp clusters details are placed into the "cluster_details.yml" file, modify the cluster_login role to use these connection details to obtin a tcken.
=> Add creation of login token from cluster details file

roles/acm/tasks/deploy.yml, roles/managed_cluster/tasks/cluster_deployment.yml
When fetching a version of the ocp for the managed cluster or an acm version from quay, could be that the required version exists not on the first page.
As a result, required version will not be fetched and deployment will fail..
To solve it, add the following filter to the query: "?filter_tag_name=like:<tag_version>".
It will query explicit version of the image, for example: 4.11 and return a list of available versions:
- 4.11.59
- 4.11.58 etc...
=> Fetch explicit ocp image / acm version from quay

Jenkinsfile
Junit files path has been changed due to the folders restructure made. Update the path to get the tests results.
=> Fix Jenkinsfile junit path

cypress/cypress/e2e/04_submariner_addon.cy.js
The addon UI test failed When there were several pages of cluster sets therefore a search (in the search bar) for the cluster name was added.
=> Added cluster search by name in the search bar in the addon cypress test

roles/acm/tasks/main.yml, roles/cluster_login/tasks/main.yml, roles/ocp/tasks/fetch_details.yml
Passwords from cluster deployment should not be printed to console output during playbook execution.
They should be placed within a separate file and fetched from there.
=> Do not expose passwords to console output

roles/ocp/tasks/creds.yml, roles/ocp/tasks/main.yml, roles/ocp/tasks/prepare.yml
In ocp role, separate cloud credentials prepare from cluster configuration prepare.
When cluster deleted, configuration is not prepared but cloud credentials could be missing.
Prepare credentials on both flows - create / destroy cluster.
=> [ocp role] Separate cloud credentials prepare

variables
Definition of bash variable should be done without spaces between key and value.
=> Fix variable definition

cypress/cypress/views/submariner/actions/submariner_actions.js
Last change added to the "testTheDataLabel" function and used within "submariner_deployment_validation" test adds big timeout to command. It cause the test to crash during the execution and thrown out with "Unautorized" error.
Reverting the change of this last to the previous state.
=> Fix cypress verification test crash

Jenkinsfile
When acm-qe will execute "backup-restore" scenario pipeline, it will provide "@post-restore" TEST_TAGS variable.
When provided, add test report suffix - "backup-restore" to the test report in order to easily identify that scenario.
=> Add "backup-restore" tests suffix to acm-qe Jenkinsfile

Jenkinsfile
In acm-qe jenkins, logs stored in a PV, so they are persistent over jobs.
Delete "logs/" dir so in case the job skipped, previous job results will not be reported.
=> Prevent previous results report in acm-qe jenkins

Jenkinsfile
Backup/Restore feature added to for Submariner in version 2.7
If backup/resore scenario triggered and ACM version lower than 2.7, skip the job
=> Add ACM version check for "backup/restore" scenario

jenkinsfiles/SubmarinerAgentPod.yaml, jenkinsfiles/aws-gcp-azure.Jenkinsfile, jenkinsfiles/base.Jenkinsfile, jenkinsfiles/env-destroy.Jenkinsfile, jenkinsfiles/gcp-vsphere.Jenkinsfile
- Add base.Jenkinsfile file that contains all stages being reused by other jenkinsfiles.
- Add aws-gcp-azure.Jenkinsfile and gcp-vsphere.Jenkinsfile jobs that will use the base file as source while applying specific job related parameters.
- Add env-destroy.Jenkinsfile job that will destroy the given environment.
- Add SubmarinerAgentPod.yaml to set the templates for the pod that an agent will use while spawned by the jenkins during job execution.
=> Add Jenkinsfiles for the standalone jenkins jobs

Dockerfile
When building container image with podman runtime, it fails when fetching rosa binary and placing it under "/usr/local/bin/". The ownership sets to a random UID and GID which cause build proccess to fail.
Fix it by adding "--no-same-owner" flag to tar command.
=> Fix ROSA binary in Dockerfile

lib/reporting/polarion_report.py
- Add "junit" string as part of the name during report search when prefix is not defined.
- Delete "polarion" directory that holds generated polarion reports before script execution to not report previous tests results.
=> Update polarion_report script

lib/submariner_test/submariner_test.sh
The "get_tests_failures" function search for the errors through the log files created during test execution.
Fix the path to search in the proper location.
=> Fix log file search path

roles/ocp/tasks/fetch_details.yml, roles/ocp/tasks/main.yml
Print all deployed clusters details as summary at the end of role execution to keep the information for the clusters in one print.
=> [OCP role] - Print clusters details as summary

roles/ocp/tasks/main.yml, roles/ocp/tasks/prepare_clusters_list.yml, roles/ocp/tasks/process.yml
- When running deployment of multiple clusters according to the configuration provided in order to reach the desired state, some clusters may be already deployed.
Those clusters should not be deployed, in order to not break the flow and messa up existing clusters.
- When running deletion of the clusters, some of the clusters may be already deleted.
Those clusters should be skipped as they are not longer exists.
In order to meet the above requirements, create lists of the clusters that should be created / deleted based on existsing state of the clusters.
Existing state of the clusters desided based on existing "metadata.json" file located within the cluster assets directory.
=> [OCP role] - Check for existing clusters during deployment

playbooks/acm.yml, playbooks/env_deploy.yml, playbooks/env_destroy.yml, playbooks/managed_cluster.yml, playbooks/ocp.yml, requirements.yml
Ansible roles responsible for deploying ACM based environment moved to a collection [1].
Update ansible requirements to fetch the collection. Update the playbooks to get the roles according to collection.
[1] - https://github.com/stolostron/ansible-collection.rhacm
=> Modify ansible collection requirements

README.md, lib/common/helper_functions.sh, run.sh
Submariner deployment/test flow uses three main environment variables as part of the flow.
One of the environment variables is - OC_CLUSTER_URL. The name of missleading, since actually, the variable expect to get the openshift cluster api url.
Rename the OC_CLUSTER_URL to OC_CLUSTER_API variable to prevent future missleading.
=> Change OC_CLUSTER_URL environment variable

README.md, lib/submariner_prepare/downstream_prepare.sh, run.sh
- Add a function that update the submariner catalog source on managed clusters
- Add --subm-catalog-update flag to the the run.sh
- Add this argument to the documentation
=> Add --subm-catalog-update flag to run.sh

README.md, jenkinsfiles/acm-qe.Jenkinsfile, lib/common/helper_functions.sh, lib/submariner_test/submariner_ui.sh, run.sh, variables
By default cypress executes the tests with "chrome" browser.
But it's not working when FIPS mode is enabled on the cluster.
Add "--test-browser" argument to control which browser should be used during cypress testing.
Add a "BROWSER" parameter to the acm-qe jenkins job.
=> Add cypress browser selection

jenkinsfiles/SubmarinerAgentPod.yaml
Update jenkins pod images reference to use digest instead of tag.
Use of the tag may not pull the latest image.
Using digest issafer to get the actual pod images every job.
=> Update jenkins pod image reference

lib/common/prerequisites.sh, lib/submariner_prepare/azure_prepare.sh
- In ACM 2.5.x, azure cli nneds to be installed in order to manually set the prerequisites.
Now, as moving to an containerized image, after azure-cli has been installed, add the "az" binary to the PATH.
- Fix the kubeconfig reference in azure gateway node prepare.
=> Fix azure-cli apply in ACM 2.5.x

jenkinsfiles/SubmarinerAgentPod.yaml, jenkinsfiles/aws-gcp-azure.Jenkinsfile, jenkinsfiles/base.Jenkinsfile
- Remove cypress UI section from the jenkinsfile as cypress UI testing
is not imprelented in release-2.5.
- Remove the "SUBMARINER_GATEWAY_RANDOM" definition as it's not
implemented in release-2.5.
- Set test image definition with digest instead of the tag in Submariner
pod definition.
=> [release-2.5] Adapt jenkins job

Dockerfile
The image built from the Dockerfile used by two different jenkins and by local execution flow.
As a result, different user could be used during creation of the container.
In order to satisfy all the users and make ansible stolostron.rhacm collection available by all users, place it in a path that would be accessible by everyone.
=> Update ansible collection install in Dockerfile

lib/submariner_deploy/submariner_deploy.sh, manifests/submariner-config.yaml
The channel version for submariner deployment now identified automativally by the submariner-addon.
As result, no need to specify the channel manually.
One more reason to remove definition of the channel from the SubmarinerConfig subscription section, is the ability to perform upgrade flow automatically.
(cherry picked from commit 0bad72b7de5b28666f1374adf219e902b413ee05)
=> Remove channel from SubmarinerConfig subscription (#433)

scripts/local_environment.sh
Podman is often installed with a Docker shim, so it gets detected as Docker even though it would be best to treat it as Podman. Reversing the detection ensures that Podman is detected as such.
=> Look for podman first

Makefile
Add "-e state=present" and "-e state=absent" to the deploy and destroy playbooks in Makefile to override definition of the state in config file.
=> Add states definition to ansible playbooks in Makefile

lib/common/helper_functions.sh
As a prerequisites of submariner deploy or test, a few steps needs to be done.
One of the steps, is to fetch the "kubeconfig" file and kubeadmin password value.
Some of the clusters might be missing the cluster kubeadmin password. Make the fetch of the password optional.
Only kubeconfig file will be mandatory.
=> Make cluster passwork fetch optional

manifests/image-content-source-policy.yaml
Recently, Openshift ROSA SME team provibited override of registry.redhat.io explicitly.
But it's allowed to override specific namespaces.
In order to allow downstream deployment of submariner on ROSA clusters and as a general deployment flow change, set the override mirror for regsitry.redhat.io to the "rhacm2" namespace.
When the image will try to fetch the image from
registry.redhat.io/rhacm2, it will be overrided by the brew internal registry.
=> Update ImageContentSourcePolicy manifest

cypress/cypress/e2e/03_submariner_deploy.cy.js
The submariner cypress deploy test failed because the deployment took longer than the time the test waited for it to be done
=> Increasing the time of wait on for the deployment of Submariner

cypress/cypress/e2e/01_submariner_deployment_validation.cy.js, cypress/cypress/e2e/02_submariner_uninstall.cy.js, cypress/cypress/e2e/03_submariner_deploy.cy.js, cypress/cypress/views/clusters/managedCluster.js, cypress/cypress/views/submariner/actions/submariner_actions.js
- Modification of the method "ClusterSetShouldExist" so that it fits many tests
-  Modification of the method "ClusterSetShouldExist"  so it will write to the logs if the cluster was found or not
- Adapting the deploy validation and deploy tests to the new form of the method
- add logs to the uninstall test
=> Add logs to cypress uninstall test

cypress/cypress.config.js, cypress/cypress/e2e/04_submariner_addon.cy.js, cypress/cypress/support/e2e.js, lib/submariner_test/submariner_ui.sh
- At the end of running each UI test, a log file will be created in /logs/ui_logs
- Add logs to submariner add on cypress test
=> Added creation of a log file for the UI tests

lib/submariner_prepare/downstream_prepare.sh, run.sh, variables
Recently, "submariner-addon" component in ACM moved under MCE. It means that now, during submariner deployment, "submariner-addon" pod requires "quay.io:443" credentials to be able to fetch the image from the quay.io:443/acm-d private repository.
Add a flow to copy the quay.io:443 credential from the hub to spoke clusters similar to the flow being done with brew credentials.
=> Add private quay credentials apply on spoke clusters

Dockerfile
In Dockerfile, move ansible collection install step after submariner user definition, so the collection will be installed under submariner user and take over any other default.
=> Modify Dockerfile ansible install steps

lib/common/prerequisites.sh, lib/submariner_deploy/submariner_deploy.sh, run.sh
Deployment of ROSA based openshift cluster had a requirement to create a node to serve as submariner gateway.
Labeling of existing node was not allowed.
Recently, it was changed.
Currently, during submariner deployment on rosa cluster, one of the worker nodes successfully labeled.
Remove the manual machineset creation steps.
=> Remove manual machineset creation for ROSA

Dockerfile, jenkinsfiles/SubmarinerAgentPod.yaml, playbooks/acm_import_cluster.yml, playbooks/managed_openshift.yml, scripts/local_environment.sh
- The image created from a Dockerfile, could be used both by jenkins CI or by any individual who would like to use automation and containerization flow, which means that users with different UID will be used. Modify ansible collection flow to be installed in a path that could be reachable by anyone without permission issues - '/usr/share/ansible/collections'.
- Add "ANSIBLE_COLLECTIONS_PATHS" environment variable to "SubmarinerAgentPod.yaml" file for jenkins and local containerized flow. That variable will point any user that will use an image to installed collection.
- Add "managed_openshift" and "acm_import_cluster" new playbooks.
=> Modify ansible collection install flow

Dockerfile, jenkinsfiles/SubmarinerAgentPod.yaml, playbooks/acm_import_cluster.yml, playbooks/managed_openshift.yml
- The image created from a Dockerfile, could be used both by jenkins CI or by any individual who would like to use automation and containerization flow, which means that users with different UID will be used. Modify ansible collection flow to be installed in a path that could be reachable by anyone without permission issues - '/usr/share/ansible/collections'.
- Add "ANSIBLE_COLLECTIONS_PATHS" environment variable to "SubmarinerAgentPod.yaml" file for jenkins and local containerized flow. That variable will point any user that will use an image to installed collection.
- Add "managed_openshift" and "acm_import_cluster" new playbooks.
=> Modify ansible collection install flow (#534)

jenkinsfiles/aws-gcp-azure.Jenkinsfile, jenkinsfiles/base.Jenkinsfile, jenkinsfiles/env-destroy.Jenkinsfile, jenkinsfiles/gcp-vsphere-rosa.Jenkinsfile, playbooks/ci/acm.yml, playbooks/ci/acm_hive_cluster.yml, playbooks/ci/acm_import_cluster.yml, playbooks/ci/managed_openshift.yml, playbooks/ci/ocp.yml
- Add the following stages to jenkins jobs:
- Deploy Managed OCP
- Import OCP into ACM Hub
- Create a dedicated CI playbooks to be able to control playbooks
execution with a condition from the configuration files.
=> Add stages to jenkins jobs

jenkinsfiles/aws-gcp-azure.Jenkinsfile, jenkinsfiles/base.Jenkinsfile, jenkinsfiles/gcp-vsphere.Jenkinsfile, playbooks/ci/acm.yml, playbooks/ci/acm_hive_cluster.yml, playbooks/ci/acm_import_cluster.yml, playbooks/ci/managed_openshift.yml, playbooks/ci/ocp.yml
- Add the following stages to jenkins jobs:
- Deploy Managed OCP
- Import OCP into ACM Hub
- Create a dedicated CI playbooks to be able to control playbooks execution with a condition from the configuration files.
=> Add stages to jenkins jobs (#540)

playbooks/acm.yml, playbooks/acm_hive_cluster.yml, playbooks/acm_import_cluster.yml, playbooks/ci/acm.yml, playbooks/ci/acm_hive_cluster.yml, playbooks/ci/acm_import_cluster.yml, playbooks/ci/env_deploy.yml, playbooks/ci/env_destroy.yml, playbooks/ci/managed_openshift.yml, playbooks/ci/ocp.yml, playbooks/env_deploy.yml, playbooks/env_destroy.yml, playbooks/managed_openshift.yml, playbooks/ocp.yml
According to ansible-lint the roles should be referenced by fqdn and not define a collection separatelly.
=> Reference ansible roles by FQDN

jenkinsfiles/acm-qe.Jenkinsfile, jenkinsfiles/base.Jenkinsfile, lib/common/prerequisites.sh, run.sh
When "subctl" binary was not built downstream, during the testing pipeline, it was fetched from the upstream (github). Once the "subctl" binary started to built downstream and shipped to the customers, the downstream testing pipeline, used it to test and validate the binary alongside with all other submarienr components. But "post-publishing" flow, which should test the submariner once it gets GA, still fetched the "subctl" from the upstream (github). The "post-publishing" pipeline, should test all submariner components once released to ensure the customer gets all the components in a working state.
Modify the "post-publishing" flow in order to fetch the "subctl" binary from the official RH registry - registry.redhat.io. Once executed with "--downstream false" flag, the execution will …
=> Modify subctl fetch from official registry

jenkinsfiles/acm-qe.Jenkinsfile, jenkinsfiles/base.Jenkinsfile, lib/common/prerequisites.sh, run.sh
When "subctl" binary was not built downstream, during the testing pipeline, it was fetched from the upstream (github). Once the "subctl" binary started to built downstream and shipped to the customers, the downstream testing pipeline, used it to test and validate the binary alongside with all other submarienr components. But "post-publishing" flow, which should test the submariner once it gets GA, still fetched the "subctl" from the upstream (github). The "post-publishing" pipeline, should test all submariner components once released to ensure the customer gets all the components in a working state.
Modify the "post-publishing" flow in order to fetch the "subctl" binary from the official RH registry - registry.redhat.io. Once executed with "--downstream false" flag, the execution will …
=> Modify subctl fetch from official registry (#561)

README.md, lib/common/helper_functions.sh, lib/submariner_deploy/submariner_deploy.sh, run.sh, variables
It's possible in submariner deployment to manually pre-label the one of the cluster nodes with GW label and during the deployment process of Submariner, that node will be used as the Submarienr Gateway node.
Add this flow to be able to test such scenario.
=> Add manual submariner GW node labeling

lib/submariner_deploy/submariner_deploy.sh
In submariner qe test scenario, osp platform will be manual labeled for the Submariner GW nodes.
=> Skip cloud creds check for OSP platform

jenkinsfiles/aws-gcp-azure.Jenkinsfile, jenkinsfiles/base.Jenkinsfile, jenkinsfiles/gcp-vsphere-rosa.Jenkinsfile
The following submariner parameters are moved from the base jenkinsfile level to the individual jobs levels.
- Globalnet
- Downstream
=> Jenkins - move specific subm params to jobs level

lib/common/helper_functions.sh, lib/common/prerequisites.sh, lib/submariner_prepare/acm_prepare_for_submariner.sh, lib/submariner_prepare/downstream_prepare.sh, lib/submariner_test/submariner_test.sh, run.sh, variables
Modify the upgrade flow to the following steps:
- Fetch existing acm hub version.
- Fetch existing submariner version.
- Increase the version of both versions above.
- Update the catalog sources of of both acm and submariner.
- Trigger the acm upgrade flow and wait for it to complete.
The improvement comes from fetching the existing installed version and not by allocating the versions from the "variables" array. It will allow to execute the upgrade from the "newer" version branch and will prevent a non matching version error.
=> Improve upgrade flow

lib/submariner_upgrade/submariner_upgrade.sh, variables
During upgrade flow, as acm hub has been upgraded, we need to verify Submariner has been upgraded as well.
Add that step to an upgrade flow.
=> Add Submariner version verify for upgrade

jenkinsfiles/SubmarinerAgentPod.yaml
Add a volume mapping to a Jenkins pod to be able to pass config file between pods and jobs if required.
=> Add volume mapping to Jenkins pod

variables
The "variables" file was missing the "DOWNSTREAM_CATALOG_SOURCE" variable statement, which lead to a downstream deployment failure.
=> Fix downstream deployment failure

lib/common/helper_functions.sh
During submariner testing an installed version should be fetched.
Fix a bug with fetching the installed version.
=> Fix submariner version fetch

variables
Modify the definition of Submariner to ACM varsion alignment to deploy always the latest z-stream submariner version available aligned to installed ACM.
=> Modify Submariner version selection

cypress/cypress/e2e/03_submariner_deploy.cy.js
UI Submariner deployment could take time to reach the fully connected state.
Increase the timeout to wait for that state.
=> Increase waiting time for cypress deployment test

lib/submariner_prepare/roks_prepare_for_submariner.sh
The function for cluster list creation merges multiple roks clusters into one single line.
Fixing this by adding a comma during list creation.
=> Fox ROKS cluster list creation

jenkinsfiles/SubmarinerAgentPod.yaml, lib/submariner_test/submariner_ui.sh
Modify the location of cypress videos and snapshot
- Modify the cypress execution command to place the tests generated
videos and snapshots into logs tests directory.
- Add command to archive the directory of videos and snapshots of
cypress within logs tests directory.
=> Modify the location of cypress videos and snapshot
