lib/submariner_prepare/validate_acm_readiness.sh
As part of the ARO platform support:
- Add "fetch_managed_cluster_by_product" function ARO cluster is an Openshift platform provided by Azure provider. In order to properly identify the ARO cluster, need to fetch the "product.open-cluster-management.io" key that should point to "ARO" value and part of the "managedclusters" output.
- Add "check_managed_clusters_available_platform" function Will check and return the clusters by specified platform. For example, aws,gcp...
- Refactor "check_available_vsphere_platform_clusters" function to "check_managed_clusters_readiness" function. No POWERSTATE state is available for the managed clusters. Checking the running state by fetching the ManagedClusterConditionAvailable. The function will check the platform that will be provided as an input.
- …
=> Fetch clusters by product

lib/submariner_prepare/downstream_mirroring_workaround.sh
A temporary workaround for the following bug:
https://issues.redhat.com/browse/ACM-2387
=> Workaround for ACM-2387

cypress/cypress.config.js, cypress/cypress/e2e/verify-deployment/submariner_deployment_validation.cy.js, cypress/cypress/fixtures/example.json, cypress/cypress/support/commands.js, cypress/cypress/support/constants.js, cypress/cypress/support/e2e.js, cypress/cypress/views/clusters/managedCluster.js, cypress/cypress/views/clusterset/clusterset.js, cypress/cypress/views/common/commonSelectors.js, cypress/cypress/views/header.js, cypress/cypress/views/submariner/actions/submariner_actions.js, cypress/package-lock.json, cypress/package.json
Add cypress testing for ACM submariner add-on UI
=> Add cypress testing init

lib/submariner_prepare/validate_acm_readiness.sh
When fetching clusters for submariner deployment, it's not enough to test that the clusters have power state - "Running". If the cluster created from a pool and set to run but not yet claimed, it will be still showed in "Running" state.
Check for the clusters Availability from the managed clusters output in addition to the above check.
=> Validate clusters availability

cypress/cypress/apis/clusterSet.js, cypress/cypress/e2e/submariner_uninstall.cy.js, cypress/cypress/e2e/verify-deployment/submariner_deployment_validation.cy.js, cypress/cypress/views/clusters/managedCluster.js, cypress/cypress/views/clusterset/clusterset.js
Add cypress testing for ACM submariner add-on UI
=> deployment validation test fix and create uninstall test

README.md, variables
Add support of submariner version for:
ACM 2.6.4 / Submariner 0.13.3
=> [release-2.6] Add support for version 0.13.3

lib/submariner_test/submariner_ui.sh
- Execute the UI tests by fetching the tests with "@e2e" tags only. That way we will be able to control the execution of the required tests only.
- Merged multiple tests results into one single junit report.
- Add "restore submariner deployment state". In case an uninstall test removed the submariner deployment, need to deploy it back in order to gather info after the end of the pipeline.
=> Update UI tests flow

cypress/cypress.config.js, cypress/cypress/e2e/01_submariner_deployment_validation.cy.js, cypress/cypress/e2e/02_submariner_uninstall.cy.js, cypress/cypress/e2e/03_submariner_deploy.cy.js, cypress/cypress/support/commands.js, lib/submariner_test/submariner_ui.sh
The api deployment pipeline and cypress are using similar environment variables.
Align the variables between both pipelines.
Aligned variables are:
- OC_CLUSTER_USER = CYPRESS_OC_CLUSTER_USER
- OC_CLUSTER_PASS = CYPRESS_OC_CLUSTER_PASS
- CLUSTERSET = CYPRESS_CLUSTERSET
- SUBMARINER_IPSEC_NATT_PORT = CYPRESS_SUBMARINER_IPSEC_NATT_PORT
=> Align cypress variables

lib/submariner_prepare/downstream_prepare.sh
Remove cpass build owner from datagrepper query.
Lately, cpass owner changed from "contra/pipeline" to a new created cpass bot user.
The build owner is not actully required and moreover eliminate the requirement to compare between the standard and CVE build.
Now, the latest build will be taken automatically.
=> Remove cpass owner from datagrepper query

Dockerfile
CI pipeline is using containerized flow for execution.
Create a Dockerfile to combine all requirements for submariner qe pipeline execution.
=> Add Dockerfile for ci pipeline

lib/common/helper_functions.sh, lib/submariner_prepare/acm_prepare_for_submariner.sh
If kubeconfig file for cluster is not found, fail the flow with message.
=> Add failure for kubeconfig not found

README.md, lib/common/helper_functions.sh
Update the Polarion input file structure based on teh recent changes.
=> Update Polarion input file doc

README.md, lib/common/prerequisites.sh, variables
- Add Submariner 0.15.0 vars
- Fetch subctl from downstream image during downstream deployment
=> Add Submariner 0.15.0 variables

Jenkinsfile
Add 8 hour timeout section to Jenkinsfile.
=> Add timeout to Jenkins job

playbooks/ocp.yml, requirements.yml, roles/ocp/README.md, roles/ocp/defaults/main.yml, roles/ocp/tasks/fetch_details.yml, roles/ocp/tasks/main.yml, roles/ocp/tasks/prepare.yml, roles/ocp/templates/install-config.yaml.j2
The role will create or destroy the ocp clusters based on the user input.
=> Add ansible role for OCP

roles/ocp/tasks/fetch_details.yml, roles/ocp/tasks/main.yml
- Add cluster console url to the final report output
- Download "openshift-install" binary to "/tmp" directory
- Delete cluster assets directory when cluster destroyed
=> Update ocp role

ansible.cfg, playbooks/acm.yml, playbooks/deploy_env.yml, roles/acm/README.md, roles/acm/defaults/main.yml, roles/acm/tasks/deploy.yml, roles/acm/tasks/main.yml, roles/acm/tasks/update_pull_secret.yml, roles/acm/templates/catalog-source.yaml.j2, roles/acm/templates/image-content-source-policy.yaml.j2, roles/acm/templates/multiclusterhub.yaml.j2, roles/acm/templates/operator-group.yaml.j2, roles/acm/templates/subscription.yaml.j2, roles/acm/vars/main.yml
- Create acm hub deploy ansible based role
- Add ansible.cfg for initial ansible configuration
=> Create ACM Hub deploy/destroy ansible role

roles/acm/tasks/deploy.yml, roles/ocp/templates/install-config.yaml.j2
For the debug purposes, add a bash representation of acm downstream snapshot query
=> ACM role - add snapshot query bash representation.

requirements.txt, requirements.yml
- Set requirements.txt file versions for ansible and related packages.
- Set requirements.yml file versions for ansible galaxy collections.
=> Set requirements files versions

playbooks/managed_cluster.yml, roles/managed_cluster/README.md, roles/managed_cluster/config-sample.yml, roles/managed_cluster/defaults/main.yml, roles/managed_cluster/tasks/cluster_deployment.yml, roles/managed_cluster/tasks/main.yml, roles/managed_cluster/tasks/prepare_secrets.yml, roles/managed_cluster/templates/cloud-secret.yaml.j2, roles/managed_cluster/templates/cluster-deployment.yaml.j2, roles/managed_cluster/templates/global-credentials.yaml.j2, roles/managed_cluster/templates/install-config-secret.yaml.j2, roles/managed_cluster/templates/install-config.yaml.j2, roles/managed_cluster/templates/klusterlet-addon-config.yaml.j2, roles/managed_cluster/templates/machine-pool.yaml.j2, roles/managed_cluster/templates/managed-cluster.yaml.j2, roles/managed_cluster/templates/private-key-secret.yaml.j2, roles/managed_cluster/templates/pull-secret.yaml.j2, roles/managed_cluster/templates/vsphere_cert.yml.j2, roles/managed_cluster/vars/main.yml
The managed_cluster role responsible for creation of managed clusters on the acm hub cluster based on the user input.
- Creates global credentials
- Creates managed clusters for the following platforms:
- AWS
- GCP
- Azure
- VMware vSphere
- The user is able to override multiple parameters to create the managed cluster based on the exact needs.
- THe role contains `config-sample.yml` file with examples for configuration.
=> Add ansible managed_cluster role

roles/ocp/README.md, roles/ocp/defaults/main.yml, roles/ocp/tasks/deploy.yml, roles/ocp/tasks/main.yml
Add the ability to specify the version of openshift to be deployed.
=> [ocp role] - Parametrize ocp version for deployment

cypress/cypress/support/commands.js, cypress/cypress/views/header.js
- Add a version check because the position of the cluster switcher menu has changed in version 3.14
- Update CSS descriptions according to version 3.14.
=> Update the cluster switcher handler for ocp 4.13

requirements.yml
- Update kubernetes.core collection to 2.4.0
- Update community.okd collection to 2.3.0
=> Update ansible collections versions

Dockerfile
As part of the framework change and movement to ansible, update Dockerfile to include ansible and its dependencies.
=> Add ansible and deps to the Dockerfile

roles/acm/README.md, roles/acm/defaults/main.yml, roles/acm/tasks/deploy.yml, roles/acm/tasks/main.yml, roles/acm/tasks/update_pull_secret.yml, roles/managed_cluster/tasks/cluster_deployment.yml, roles/managed_cluster/tasks/main.yml, roles/managed_cluster/tasks/prepare_secrets.yml, roles/ocp/tasks/fetch_details.yml
Change the "cluster_url" to "cluster_api" variable across all roles to make it more understandable.
=> Change "cluster_url" to "cluster_api" variable

cypress/cypress/views/clusterset/clusterset.js
The clusterset deletion failed because wrong css description
=> Fix the clusterset deletion in the addon test

jenkinsfiles/acm-qe.Jenkinsfile
Jenkinsfile used for acm-qe submariner pipeline relocated from the root of the repository to "jenkinsfiles/" directory.
=> Relocate acm-qe Jenkinsfile

jenkinsfiles/acm-qe.Jenkinsfile
Jenkinsfile used for acm-qe submariner pipeline relocated from the root of the repository to "jenkinsfiles/" directory.
=> [release-2.7] - Relocate acm-qe Jenkinsfile

jenkinsfiles/acm-qe.Jenkinsfile
Jenkinsfile used for acm-qe submariner pipeline relocated from the root of the repository to "jenkinsfiles/" directory.
=> [release-2.6] - Relocate acm-qe Jenkinsfile

jenkinsfiles/acm-qe.Jenkinsfile
Jenkinsfile used for acm-qe submariner pipeline relocated from the root of the repository to "jenkinsfiles/" directory.
=> [release-2.5] - Relocate acm-qe Jenkinsfile

cypress/cypress/e2e/03_submariner_deploy.cy.js
Added a check if there is already a cluster set named Submariner. 
Added "e2e" tag so that the test will be part of the flow.
=> Adjusting the deploy UI test to be part of the flow.

variables
Changed the submariner version to 0.12.4 on ACM 2.5.9
=> Edit variables file

Makefile, docs/execution_and_development.md
Update local development environment variable.
Update the variable from OC_CLUSTER_URL to OC_CLUSTER_API according to the following patch:
https://github.com/stolostron/acmqe-mcn-test/pull/390
=> Update local dev vars

jenkinsfiles/acm-qe.Jenkinsfile
As OC_CLUSTER_URL has been updated to OC_CLUSTER_API [1], the acm-qe jenkinsfile job needs to be updated with the the change as well.
[1] - https://github.com/stolostron/acmqe-mcn-test/pull/390
=> Update acm-qe.Jenkinsfile to update env var

README.md, docs/local_execution.md
Update README file to include the information about stolostron.rhacm collection.
=> Update README file

jenkinsfiles/aws-gcp-azure.Jenkinsfile, jenkinsfiles/base.Jenkinsfile
Add aws-gcp-azure job scenario for ACM-2.5-Submariner-0.12
=> [release-2.5] - Add jenkins job

jenkinsfiles/SubmarinerAgentPod.yaml
Add SubmarinerAgentPod.yaml file for jenkins job pod description.
=> [release-2.5] - Add SubmarinerAgentPod file

jenkinsfiles/base.Jenkinsfile, playbooks/acm_hive_cluster.yml, playbooks/env_deploy.yml, playbooks/env_destroy.yml
The "managed_cluster" role has been renamed to "acm_hive_cluster".
Rename all the references within playbooks and base.Jenkinsfile.
=> Update renamed role

jenkinsfiles/SubmarinerAgentPod.yaml, jenkinsfiles/aws-gcp-azure.Jenkinsfile, jenkinsfiles/base.Jenkinsfile, jenkinsfiles/gcp-vsphere.Jenkinsfile, playbooks/acm_hive_cluster.yml, playbooks/env_deploy.yml, playbooks/env_destroy.yml
Add the following jobs to release-2.7:
- acm-2.7-subm-0.14-aws-gcp-azure
- acm-2.7-subm-0.14-gcp-vsphere
=> [release-2.7] - Add jenkinsfiles for jobs

docs/config-sample.yml
According to the changes made in stolostron.rhacm collection, updated parameters with in the config-sample.yml file.
=> Update config-sample.yml file

jenkinsfiles/SubmarinerAgentPod.yaml, jenkinsfiles/aws-gcp-azure.Jenkinsfile, jenkinsfiles/base.Jenkinsfile, playbooks/acm_hive_cluster.yml, playbooks/env_deploy.yml, playbooks/env_destroy.yml
Add aws-gcp-azure jenkins job scenario for submariner.
=> [release-2.6] - Add jenkins job for submariner

Makefile, scripts/local_environment.sh
Runtime selection bacome a parameter.
By default, it will use "docker".
A user could change the runtime engine to be used with:
make env-deploy CONF=... RUNTIME=docker
make env-deploy CONF=... RUNTIME=podman
=> Add runtime selection as parameter to Makefile

jenkinsfiles/acm-qe.Jenkinsfile
update the submariner catalog and test the upgrade according to the @post-upgrade and @pre-upgrade tags
=> Update jenkinsfile to include upgrade job

cypress/cypress/e2e/01_submariner_deployment_validation.cy.js, cypress/cypress/e2e/02_submariner_uninstall.cy.js, cypress/cypress/e2e/03_submariner_deploy.cy.js, cypress/cypress/views/clusters/managedCluster.js, cypress/cypress/views/submariner/actions/submariner_actions.js
- Modification of the method "ClusterSetShouldExist" so that it fits many tests
- Adapting the deploy validation and deploy tests to the new form of the method
- add logs to the uninstall test
=> [release-2.7] Add logs to cypress uninstall test (#478)

cypress/cypress/e2e/01_submariner_deployment_validation.cy.js, cypress/cypress/e2e/02_submariner_uninstall.cy.js, cypress/cypress/e2e/03_submariner_deploy.cy.js, cypress/cypress/views/clusters/managedCluster.js, cypress/cypress/views/submariner/actions/submariner_actions.js
- Modification of the method "ClusterSetShouldExist" so that it fits many tests
- Adapting the deploy validation and deploy tests to the new form of the method
- add logs to the uninstall test
=> [release-2.6] Add logs to cypress uninstall test (#478)

cypress/cypress.config.js, cypress/cypress/e2e/04_submariner_addon.cy.js, cypress/cypress/support/e2e.js, lib/submariner_test/submariner_ui.sh
At the end of running each UI test, a log file will be created
=> [release-2.7] Added creation of a log file for the UI tests (#482)

cypress/cypress.config.js, cypress/cypress/e2e/04_submariner_addon.cy.js, cypress/cypress/support/e2e.js, lib/submariner_test/submariner_ui.sh
At the end of running each UI test, a log file will be created
=> [release-2.6] Added creation of a log file for the UI tests (#482)

cypress/cypress/e2e/03_submariner_deploy.cy.js, cypress/cypress/views/submariner/actions/submariner_actions.js
add logs to monitor the steps on cypress submariner deploy test.
=> Add logs to cypress submariner deploy test

cypress/cypress/e2e/03_submariner_deploy.cy.js, cypress/cypress/views/submariner/actions/submariner_actions.js
add logs to monitor the steps on cypress submariner deploy test.
=> [release-2.7] Add logs to cypress submariner deploy test (#486)

jenkinsfiles/README.md
The README file describes the structure of submariner qe jobs.
=> Add README file to jenkinsfiles section

README.md, lib/common/prerequisites.sh, lib/submariner_deploy/submariner_deploy.sh, lib/submariner_prepare/validate_acm_readiness.sh, variables
Add deployment support for IBM Power platform architecture.
=> Add IBM Power platform support

README.md, docs/prerequisites.md
Prerequisites file contains steps to meet the environment to submariner sutomation execution.
=> Add prerequisites file to the documentation

docs/local_execution.md
The link to the config sample file was broken, and therefore was updated.
=> Fix the link to the config sample file on local_execution.md

Makefile
Add test type to be able to define during Makefile execution.
=> Add test type to Makefile execution

Dockerfile, jenkinsfiles/SubmarinerAgentPod.yaml
In order to avoid permission issues during Jenkins job execution, set the UID of the user that is used in Jenkins.
=> Set user UID during creation in Dockerfile

jenkinsfiles/base.Jenkinsfile
The "clusters_details.yml" file path, which contains connection informtation of deployed clusters, has been modified and by default located under - "logs/clusters_details.yml" path.
Modifying the path within the Jenkinsfile.
=> Modify clusters details path in Jenkinsfile

playbooks/ci/env_deploy.yml, playbooks/ci/env_destroy.yml
Add ansible playbooks that will ve used for jenkins ci jobs. The playbooks will control execution of different roles.
=> Add ci playbooks

jenkinsfiles/gcp-vsphere-rosa.Jenkinsfile
Add rosa platform to gcp-vsphere job to become gcp-vsphere-rosa job.
=> Modify jenkins job

jenkinsfiles/gcp-vsphere-rosa.Jenkinsfile
Rename jenkins job gcp-vsphere to gcp-vsphere-rosa and add ROSA platform.
=> Rename Jenkins job

jenkinsfiles/gcp-vsphere-rosa.Jenkinsfile
Rename jenkins job gcp-vsphere to gcp-vsphere-rosa and add ROSA platform.
=> [release-2.7] - Rename jenkins job

jenkinsfiles/gcp-vsphere-aro.Jenkinsfile
Change ROSA platform testing to ARO.
Modify the name of the job and config to be used.
=> Update jenkins job name and config

jenkinsfiles/SubmarinerAgentPod.yaml, requirements.yml
- Update RHACM collection version to v0.0.3
- Update test image digest
=> Update RHACM collection version

README.md, lib/submariner_prepare/validate_acm_readiness.sh, variables
Add OpenStack platform support for Submariner deployment and testing.
=> Add OSP platform support

jenkinsfiles/aws-gcp-azure.Jenkinsfile, jenkinsfiles/base.Jenkinsfile, jenkinsfiles/gcp-vsphere-rosa.Jenkinsfile
Add the manual cluster node labeling as Submariner GW to jenkins flow.
=> Add manual GW label to jenkins flow

jenkinsfiles/aws-gcp-azure.Jenkinsfile, jenkinsfiles/base.Jenkinsfile, jenkinsfiles/gcp-vsphere-rosa.Jenkinsfile
Add the manual cluster node labeling as Submariner GW to jenkins flow.
=> Add manual GW label to jenkins flow (#591)

jenkinsfiles/aws-gcp-azure.Jenkinsfile, jenkinsfiles/base.Jenkinsfile, jenkinsfiles/gcp-osp-aro.Jenkinsfile, jenkinsfiles/gcp-vsphere-rosa.Jenkinsfile
Rearrange the following parameters from the base level to the individual job level.
- PLATFORM
- SUBMARINER_GATEWAY_RANDOM
- NODE_TO_LABEL_AS_GW
=> Rearrage jenkins job parameters

jenkinsfiles/aws-gcp-azure.Jenkinsfile, jenkinsfiles/base.Jenkinsfile, jenkinsfiles/gcp-osp-aro.Jenkinsfile, jenkinsfiles/gcp-vsphere-rosa.Jenkinsfile
Rearrange the following parameters from the base level to the individual job level.
- PLATFORM
- SUBMARINER_GATEWAY_RANDOM
- NODE_TO_LABEL_AS_GW
=> Rearrage jenkins job parameters (#595)

README.md, lib/common/helper_functions.sh, lib/submariner_prepare/acm_prepare_for_submariner.sh, lib/submariner_prepare/downstream_prepare.sh, run.sh, variables
The upgrade flow will process the following steps:
- Update the catalog source of submariner
- Update the catalog source of acm
- Upgrade ACM and Submariner
=> Add upgrade flow

README.md, lib/common/helper_functions.sh, lib/submariner_prepare/acm_prepare_for_submariner.sh, lib/submariner_prepare/downstream_prepare.sh, run.sh, variables
The upgrade flow will process the following steps:
- Update the catalog source of submariner
- Update the catalog source of acm
- Upgrade ACM and Submariner
=> Add upgrade flow (#602)

lib/submariner_prepare/downstream_prepare.sh, lib/submariner_upgrade/submariner_upgrade.sh, run.sh
Extract upgrade steps into separate files in order to create visibility and ease of maintenance.
=> Extract upgrade steps

jenkinsfiles/upgrade.Jenkinsfile
Add a jenkins job to support the upgrade flow.
=> Add upgrade jenkins job

jenkinsfiles/upgrade.Jenkinsfile
Add a jenkins job to support the upgrade flow.
=> Add upgrade jenkins job (#606)

lib/submariner_upgrade/submariner_upgrade.sh
After ACM Hub gets upgraded, verify for each submariner cluster that the connection is established between each of submariner clusters.
=> Improve Submariner check after upgrade

jenkinsfiles/upgrade.Jenkinsfile
When a "Base env" job finished with "UNSTABLE" job state, the Upgrade job should proceed to the upgrade steps.
If the "Base env" job called by the Upgrade job failed, the rest of upgrade job steps should be skipped and the job should be set as "NOT_BUILT".
=> Update Upgrade job condition

jenkinsfiles/upgrade.Jenkinsfile
When a "Base env" job finished with "UNSTABLE" job state, the Upgrade job should proceed to the upgrade steps.
If the "Base env" job called by the Upgrade job failed, the rest of upgrade job steps should be skipped and the job should be set as "NOT_BUILT".
=> Update Upgrade job condition (#628)

lib/common/prerequisites.sh, lib/submariner_deploy/submariner_deploy.sh, lib/submariner_prepare/roks_prepare_for_submariner.sh, lib/submariner_prepare/validate_acm_readiness.sh, manifests/tigera_api.yaml, requirements.txt, run.sh, variables
Add deployment and testing support for ROKS clusters platform.
=> Add ROKS platform support

lib/reporting/polarion.sh
Since all the flow is running inside containers with all the requirements pre-installed, no separate install process for report is longer required.
=> Remove install steps for report polarion flow

requirements.yml
Increase RHACM collection version requirement to - v0.0.5
=> Modify RHACM collection version requirement

requirements.yml
Increase RHACM collection version requirement to - v0.0.5
=> Modify RHACM collection version requirement (#733)

lib/common/helper_functions.sh
Reverts stolostron/acmqe-mcn-test#743
=> Revert "Fix submariner version fetch"

jenkinsfiles/SubmarinerAgentPod.yaml
The new jenkins image includes a collection patch for scale/perf team automation deployment.
=> Update Jenkins agent image

jenkinsfiles/base.Jenkinsfile
Revert the change that was made for managed openshift stage in Jenkinsfile.
The change was made as part of creation of a job for perf / scale team.
This change created a bug, which prevented the execution of the requested staged in CI jobs.
Reverting the change to unblock the job execution.
=> Revert Jenkinsfile change for ManagedOpenshift stage
